export const BOOKS_FETCH_REQUEST = 'BOOKS_FETCH_REQUEST';
export const BOOKS_FETCH_SUCCESS = 'BOOKS_FETCH_SUCCESS';
export const BOOKS_FETCH_FAILURE = 'BOOKS_FETCH_FAILURE';

export const USERS_FETCH_REQUEST = 'USERS_FETCH_REQUEST';
export const USERS_FETCH_SUCCESS = 'USERS_FETCH_SUCCESS';
export const USERS_FETCH_FAILURE = 'USERS_FETCH_FAILURE';

export const CHECK_OUTS_FETCH_REQUEST = 'CHECK_OUTS_FETCH_REQUEST';
export const CHECK_OUTS_FETCH_SUCCESS = 'CHECK_OUTS_FETCH_SUCCESS';
export const CHECK_OUTS_FETCH_FAILURE = 'CHECK_OUTS_FETCH_FAILURE';

// TODO: Define and Export Check-Out Action Types
export const CHECK_OUT_CREATE_REQUEST = 'CHECK_OUTS_CREATE_REQUEST';
export const CHECK_OUT_CREATE_SUCCESS = 'CHECK_OUTS_CREATE_SUCCESS';
export const CHECK_OUT_CREATE_FAILURE = 'CHECK_OUTS_CREATE_FAILURE';

// TODO: Define and Export Check-In Action Types

export const SELECT_USER = 'SELECT_USER';
