export const BOOKS_FETCH_REQUEST = "BOOKS_FETCH_REQUEST";
export const BOOKS_FETCH_SUCCESS = "BOOKS_FETCH_SUCCESS";
export const BOOKS_FETCH_FAILURE = "BOOKS_FETCH_FAILURE";

export const USERS_FETCH_REQUEST = "USERS_FETCH_REQUEST";
export const USERS_FETCH_SUCCESS = "USERS_FETCH_SUCCESS";
export const USERS_FETCH_FAILURE = "USERS_FETCH_FAILURE";
